### ISSUE TITLE
Ability to get signal strength in percentage or quality

### ISSUE THREAD

**Issue by eakteam** [TheAndroidMaster/SignalStrengths#2]
It should be useful to calculate the percentage of signal for GSM , CDMA or LTE

**Comment by fennifith** [comment]
This can already be done pretty easily.
GSM: `SignalStrengths.get(SignalStrengths.METHOD_GSM_DBM, signalStrength)` or similar
CDMA: `SignalStrengths.get(SignalStrengths.METHOD_CDMA_DBM, signalStrength)` or similar
LTE: `SignalStrengths.get(SignalStrengths.METHOD_LTE_DBM, signalStrength)` or similar

Marking this as invalid and closing. Feel free to reopen if you have any other concerns.
